services:
  postgres:
    container_name: mtp_db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: mt_planner
      POSTGRES_USER: mtp_admin
      POSTGRES_PASSWORD: mtp_admin
    ports:
      - "5432:5432"
    volumes:
      - mtp_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: mtp_cache
    image: redis:8.6.1-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass mtp_token
    ports:
      - "6379:6379"

volumes:
  mtp_data:
